# Generated by Django 4.2 on 2023-05-16 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantity",
            new_name="qty",
        ),
    ]
